/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef VMCPUTABLE_H
#define VMCPUTABLE_H

/* function declarations */
void init_vmCpuTable(void);
void initialize_table_vmCpuTable(void);
Netsnmp_Node_Handler vmCpuTable_handler;
Netsnmp_First_Data_Point  vmCpuTable_get_first_data_point;
Netsnmp_Next_Data_Point   vmCpuTable_get_next_data_point;

void vmCpuTable_createEntryByIndex(long, long);
void vmCpuTable_removeEntryByIndex(long, long);


/* column number definitions for table vcpuTable */
#define COLUMN_VMCPUINDEX       1
#define COLUMN_VMCPUCORETIME    2

#endif /* VMCPUTABLE_H */
