/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef VMCPUAFFINITYTABLE_H
#define VMCPUAFFINITYTABLE_H

/* function declarations */
void init_vmCpuAffinityTable(void);
void initialize_table_vmCpuAffinityTable(void);
Netsnmp_Node_Handler vmCpuAffinityTable_handler;
Netsnmp_First_Data_Point  vmCpuAffinityTable_get_first_data_point;
Netsnmp_Next_Data_Point   vmCpuAffinityTable_get_next_data_point;

void vmCpuAffinityTable_createEntryByIndex(long, long, long);
void vmCpuAffinityTable_removeEntryByIndex(long, long, long);

/* column number definitions for table vmCpuAffinityTable */
#define COLUMN_VMCPUPHYSINDEX		1
#define COLUMN_VMCPUAFFINITY		2

#endif /* VCPUAFFINITYTABLE_H */
