/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "vmCpuTable.h"
#include "globalHandler.h"

/* Prototype declarations */


/** Initializes the vmCpuTable module */
void
init_vmCpuTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_vmCpuTable();
}

/* # Determine the first/last column names */

/** Initialize the vmCpuTable table by defining its contents and how it's structured */
void
initialize_table_vmCpuTable(void)
{
    const oid vmCpuTable_oid[] = {1,3,6,1,2,1,VM_MIB_OID,1,5};
    const size_t vmCpuTable_oid_len   = OID_LENGTH(vmCpuTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("vmCpuTable:init", "initializing table vmCpuTable\n"));

    reg = netsnmp_create_handler_registration(
              "vmCpuTable",     vmCpuTable_handler,
              vmCpuTable_oid, vmCpuTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: vmIndex */
                           ASN_INTEGER,  /* index: vmCpuIndex */
                           0);
    table_info->min_column = COLUMN_VMCPUINDEX;
    table_info->max_column = COLUMN_VMCPUCORETIME;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = vmCpuTable_get_first_data_point;
    iinfo->get_next_data_point  = vmCpuTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct vmCpuTable_entry {
    /* Index values */
    long vmIndex;
    long vmCpuIndex;

    /* Illustrate using a simple linked list */
    int   valid;
    struct vmCpuTable_entry *next;
};

struct vmCpuTable_entry  *vmCpuTable_head;

/* create a new row in the (unsorted) table */
struct vmCpuTable_entry *
vmCpuTable_createEntry(long vmIndex, long vmCpuIndex) {
    struct vmCpuTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct vmCpuTable_entry);
    if (!entry)
        return NULL;

    entry->vmIndex = vmIndex;
    entry->vmCpuIndex = vmCpuIndex;
    entry->next = vmCpuTable_head;
    vmCpuTable_head = entry;
    return entry;
}
void
vmCpuTable_createEntryByIndex(long vmIndex, long vmCpuIndex) {
    (void)vmCpuTable_createEntry(vmIndex, vmCpuIndex);
}

/* remove a row from the table */
void
vmCpuTable_removeEntry( struct vmCpuTable_entry *entry ) {
    struct vmCpuTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = vmCpuTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        vmCpuTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
void
vmCpuTable_removeEntryByIndex(long vmIndex, long vmCpuIndex) {
    struct vmCpuTable_entry *ptr, *prev;

    for ( ptr  = vmCpuTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr->vmIndex == vmIndex && ptr->vmCpuIndex == vmCpuIndex )
            break;
    }

    vmCpuTable_removeEntry(ptr);
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
vmCpuTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = vmCpuTable_head;
    return vmCpuTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
vmCpuTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct vmCpuTable_entry *entry = (struct vmCpuTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->vmIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->vmCpuIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the vmCpuTable table */
int
vmCpuTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct vmCpuTable_entry          *table_entry;

    uint64_t val64;
    U64 vmCpuCoreTime;

    DEBUGMSGTL(("vmCpuTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmCpuTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_VMCPUINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->vmCpuIndex);
                break;
            case COLUMN_VMCPUCORETIME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                val64 = gh_getVcpuTable_vcpuCpuTime(table_entry->vmIndex,
                                                    table_entry->vmCpuIndex);
                vmCpuCoreTime.high = (val64 >> 32) & 0xffffffff;
                vmCpuCoreTime.low = val64 & 0xffffffff;

                snmp_set_var_typed_value( request->requestvb, ASN_COUNTER64,
                                          &vmCpuCoreTime, sizeof(vmCpuCoreTime));
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
