/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "vmCpuAffinityTable.h"
#include "globalHandler.h"

/** Initializes the vmCpuAffinityTable module */
void
init_vmCpuAffinityTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_vmCpuAffinityTable();
}

/* # Determine the first/last column names */

/** Initialize the vmCpuAffinityTable table by defining its contents and how it's structured */
void
initialize_table_vmCpuAffinityTable(void)
{
    const oid vmCpuAffinityTable_oid[] = {1,3,6,1,2,1,VM_MIB_OID,1,6};
    const size_t vmCpuAffinityTable_oid_len   = OID_LENGTH(vmCpuAffinityTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("vmCpuAffinityTable:init", "initializing table vmCpuAffinityTable\n"));

    reg = netsnmp_create_handler_registration(
              "vmCpuAffinityTable",     vmCpuAffinityTable_handler,
              vmCpuAffinityTable_oid, vmCpuAffinityTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: vmIndex */
                           ASN_INTEGER,  /* index: vmCpuIndex */
                           ASN_INTEGER,  /* index: vmCpuPhysIndex */
                           0);
    table_info->min_column = COLUMN_VMCPUPHYSINDEX;
    table_info->max_column = COLUMN_VMCPUAFFINITY;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = vmCpuAffinityTable_get_first_data_point;
    iinfo->get_next_data_point  = vmCpuAffinityTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct vmCpuAffinityTable_entry {
    /* Index values */
    long vmIndex;
    long vmCpuIndex;
    long vmCpuPhysIndex;

    /* Column values */
    long vmCpuAffinity;

    /* Illustrate using a simple linked list */
    int   valid;
    struct vmCpuAffinityTable_entry *next;
};

struct vmCpuAffinityTable_entry  *vmCpuAffinityTable_head;

/* create a new row in the (unsorted) table */
struct vmCpuAffinityTable_entry *
vmCpuAffinityTable_createEntry(long vmIndex, long vmCpuIndex,
                               long vmCpuPhysIndex)
{
    struct vmCpuAffinityTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct vmCpuAffinityTable_entry);
    if (!entry)
        return NULL;

    entry->vmIndex = vmIndex;
    entry->vmCpuIndex = vmCpuIndex;
    entry->vmCpuPhysIndex = vmCpuPhysIndex;
    entry->next = vmCpuAffinityTable_head;
    vmCpuAffinityTable_head = entry;
    return entry;
}
void
vmCpuAffinityTable_createEntryByIndex(long vmIndex, long vmCpuIndex,
                                      long vmCpuPhysIndex)
{
    (void)vmCpuAffinityTable_createEntry(vmIndex, vmCpuIndex, vmCpuPhysIndex);
}

/* remove a row from the table */
void
vmCpuAffinityTable_removeEntry( struct vmCpuAffinityTable_entry *entry ) {
    struct vmCpuAffinityTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = vmCpuAffinityTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        vmCpuAffinityTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
void
vmCpuAffinityTable_removeEntryByIndex(long vmIndex, long vmCpuIndex,
                                      long vmCpuPhysIndex)
{
    struct vmCpuAffinityTable_entry *ptr, *prev;

    for ( ptr  = vmCpuAffinityTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr->vmIndex == vmIndex && ptr->vmCpuIndex == vmCpuIndex
             && ptr->vmCpuPhysIndex == vmCpuPhysIndex ) {
            break;
        }
    }

    vmCpuAffinityTable_removeEntry(ptr);
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
vmCpuAffinityTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = vmCpuAffinityTable_head;
    return vmCpuAffinityTable_get_next_data_point(my_loop_context,
                                                  my_data_context,
                                                  put_index_data,  mydata );
}

netsnmp_variable_list *
vmCpuAffinityTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct vmCpuAffinityTable_entry *entry = (struct vmCpuAffinityTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->vmIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->vmCpuIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->vmCpuPhysIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the vmCpuAffinityTable table */
int
vmCpuAffinityTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct vmCpuAffinityTable_entry          *table_entry;
    long val;
    int ret;

    DEBUGMSGTL(("vmCpuAffinityTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmCpuAffinityTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_VMCPUPHYSINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->vmCpuPhysIndex);
                break;
            case COLUMN_VMCPUAFFINITY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                val = gh_getVcpuAffinityTable_vcpuAffinity(
                    table_entry->vmIndex,
                    table_entry->vmCpuIndex,
                    table_entry->vmCpuPhysIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            val);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmCpuAffinityTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_VMCPUAFFINITY:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmCpuAffinityTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_VMCPUAFFINITY:
                /* TODO */
                /*
                  table_entry->old_vmCpuAffinity = table_entry->vmCpuAffinity;
                  table_entry->vmCpuAffinity     = *request->requestvb->val.integer;
                */
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmCpuAffinityTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_VMCPUAFFINITY:
                /* TODO */
                /*
                  table_entry->vmCpuAffinity     = table_entry->old_vmCpuAffinity;
                  table_entry->old_vmCpuAffinity = 0;
                */
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
