/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17798 2009-10-27 06:44:54Z magfr $
 */
#ifndef VM_HYPERVISOR_H
#define VM_HYPERVISOR_H

/* function declarations */
void init_vmHypervisor(void);
Netsnmp_Node_Handler handle_vmHvSoftware;
Netsnmp_Node_Handler handle_vmHvVersion;
Netsnmp_Node_Handler handle_vmHvObjectID;
Netsnmp_Node_Handler handle_vmHvUpTime;

#endif /* VM_HYPERVISOR_H */
