/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef VMNETWORKTABLE_H
#define VMNETWORKTABLE_H

/* function declarations */
void init_vmNetworkTable(void);
void initialize_table_vmNetworkTable(void);
Netsnmp_Node_Handler vmNetworkTable_handler;
Netsnmp_First_Data_Point  vmNetworkTable_get_first_data_point;
Netsnmp_Next_Data_Point   vmNetworkTable_get_next_data_point;

void vmNetworkTable_createEntryByIndex(long, long);
void vmNetworkTable_removeEntryByIndex(long, long);

/* column number definitions for table vmNetworkTable */
#define COLUMN_VMNETWORKINDEX		1
#define COLUMN_VMNETWORKIFINDEX		2
#define COLUMN_VMNETWORKPARENT		3
#define COLUMN_VMNETWORKMODEL		4
#define COLUMN_VMNETWORKPHYSADDRESS		5

#endif /* VMNETWORKTABLE_H */
