/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef VMSTORAGETABLE_H
#define VMSTORAGETABLE_H

/* function declarations */
void init_vmStorageTable(void);
void initialize_table_vmStorageTable(void);
Netsnmp_Node_Handler vmStorageTable_handler;
Netsnmp_First_Data_Point  vmStorageTable_get_first_data_point;
Netsnmp_Next_Data_Point   vmStorageTable_get_next_data_point;

void vmStorageTable_createEntryByIndex(long, long);
void vmStorageTable_removeEntryByIndex(long, long);

/* column number definitions for table vmStorageTable */
#define COLUMN_VMSTORAGEVMINDEX                 1
#define COLUMN_VMSTORAGEINDEX                   2
#define COLUMN_VMSTORAGEPARENT                  3
#define COLUMN_VMSTORAGESOURCETYPE              4
#define COLUMN_VMSTORAGESOURCETYPESTRING        5
#define COLUMN_VMSTORAGERESOURCEID              6
#define COLUMN_VMSTORAGEACCESS                  7
#define COLUMN_VMSTORAGEMEDIATYPE               8
#define COLUMN_VMSTORAGEMEDIATYPESTRING         9
#define COLUMN_VMSTORAGESIZEUNIT                10
#define COLUMN_VMSTORAGEDEFINEDSIZE             11
#define COLUMN_VMSTORAGEALLOCATEDSIZE           12
#define COLUMN_VMSTORAGEREADIOS                 13
#define COLUMN_VMSTORAGEWRITEIOS                14
#define COLUMN_VMSTORAGEREADOCTETS              15
#define COLUMN_VMSTORAGEWRITEOCTETS             16


#endif /* VMSTORAGETABLE_H */
