/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */

#include <stdint.h>
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "vmTable.h"
#include "globalHandler.h"

/*
 * Prototype declarations
 */
struct vmTable_entry * vmTable_createEntry(long);
void vmTable_removeEntry(struct vmTable_entry *);


/** Initializes the vmTable module */
void
init_vmTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_vmTable();
}

/* # Determine the first/last column names */

/** Initialize the vmTable table by defining its contents and how it's structured */
void
initialize_table_vmTable(void)
{
    const oid vmTable_oid[] = {1,3,6,1,2,1,VM_MIB_OID,1,4};
    const size_t vmTable_oid_len   = OID_LENGTH(vmTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("vmTable:init", "initializing table vmTable\n"));

    reg = netsnmp_create_handler_registration(
              "vmTable",     vmTable_handler,
              vmTable_oid, vmTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: vmIndex */
                           0);
    table_info->min_column = COLUMN_VMINDEX;
    table_info->max_column = COLUMN_VMCPUTIME;

    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = vmTable_get_first_data_point;
    iinfo->get_next_data_point  = vmTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;

    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct vmTable_entry {
    /* Index values */
    long vmIndex;

    /* Illustrate using a simple linked list */
    int   valid;
    struct vmTable_entry *next;
};

struct vmTable_entry  *vmTable_head;

/* create a new row in the (unsorted) table */
void vmTable_createEntryByIndex(long vmIndex) {
    (void)vmTable_createEntry(vmIndex);
}
struct vmTable_entry *
vmTable_createEntry(long  vmIndex) {
    struct vmTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct vmTable_entry);
    if (!entry)
        return NULL;

    entry->vmIndex = vmIndex;
    entry->next = vmTable_head;
    vmTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
vmTable_removeEntry( struct vmTable_entry *entry ) {
    struct vmTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = vmTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        vmTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

void
vmTable_removeEntryByIndex(long vmIndex) {
    struct vmTable_entry *ptr, *prev;

    for ( ptr  = vmTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr->vmIndex == vmIndex )
            break;
    }
    vmTable_removeEntry(ptr);
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
vmTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = vmTable_head;
    return vmTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
vmTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct vmTable_entry *entry = (struct vmTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->vmIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}

/** handles requests for the vmTable table */
int
vmTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct vmTable_entry          *table_entry;
    int ret;

    /* Columns */
    char vmName[256];
    size_t vmName_len;
    unsigned char vmUUID[16];
    size_t vmUUID_len;
    char vmOSType[256];
    size_t vmOSType_len;
    long vmAdminState;
    long vmOperState;
    long vmAutoStart;
    long vmPersistent;
    long vmCurCpuNumber;
    long vmMinCpuNumber;
    long vmMaxCpuNumber;
    long vmMemUnit;
    long vmCurMem;
    long vmMinMem;
    long vmMaxMem;
    unsigned long vmUpTime;
    U64 vmCpuTime;
    uint64_t val64;


    DEBUGMSGTL(("vmTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_VMINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->vmIndex);
                break;
            case COLUMN_VMNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmName_len = gh_getVmTable_vmName(table_entry->vmIndex, vmName,
                                                  sizeof(vmName));

                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          vmName, vmName_len);
                break;
            case COLUMN_VMUUID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmUUID_len = gh_getVmTable_vmUUID(table_entry->vmIndex,
                                                  vmUUID);
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          vmUUID, vmUUID_len);
                break;
            case COLUMN_VMOSTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmOSType_len = gh_getVmTable_vmOSType(table_entry->vmIndex,
                                                      vmOSType,
                                                      sizeof(vmOSType));

                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          vmOSType, vmOSType_len);
                break;
            case COLUMN_VMADMINSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmAdminState = gh_getVmTable_vmAdminState(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmAdminState);
                break;
            case COLUMN_VMOPERSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmOperState = gh_getVmTable_vmOperState(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmOperState);
                break;
            case COLUMN_VMAUTOSTART:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmAutoStart = gh_getVmTable_vmAutoStart(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmAutoStart);
                break;
            case COLUMN_VMPERSISTENT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmPersistent = gh_getVmTable_vmPersistent(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmPersistent);
                break;
            case COLUMN_VMCURCPUNUMBER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmCurCpuNumber
                    = gh_getVmTable_vmCurCpuNumber(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmCurCpuNumber);
                break;
            case COLUMN_VMMINCPUNUMBER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmMinCpuNumber
                    = gh_getVmTable_vmMinCpuNumber(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmMinCpuNumber);
                break;
            case COLUMN_VMMAXCPUNUMBER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmMaxCpuNumber
                    = gh_getVmTable_vmMaxCpuNumber(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmMaxCpuNumber);
                break;
            case COLUMN_VMMEMUNIT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmMemUnit = gh_getVmTable_vmMemUnit(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmMemUnit);
                break;
            case COLUMN_VMCURMEM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmCurMem = gh_getVmTable_vmCurMem(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmCurMem);
                break;
            case COLUMN_VMMINMEM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmMinMem = gh_getVmTable_vmMinMem(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmMinMem);
                break;
            case COLUMN_VMMAXMEM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmMaxMem = gh_getVmTable_vmMaxMem(table_entry->vmIndex);

                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            vmMaxMem);
                break;
            case COLUMN_VMUPTIME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                vmUpTime = gh_getVmTable_vmUpTime(table_entry->vmIndex);

                snmp_set_var_typed_value( request->requestvb, ASN_TIMETICKS,
                                          &vmUpTime, sizeof(vmUpTime));
                break;
            case COLUMN_VMCPUTIME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                val64 = gh_getVmTable_vmCpuTime(table_entry->vmIndex);
                vmCpuTime.high = (val64 >> 32) & 0xffffffff;
                vmCpuTime.low = val64 & 0xffffffff;

                snmp_set_var_typed_value( request->requestvb, ASN_COUNTER64,
                                          &vmCpuTime, sizeof(vmCpuTime));
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_VMADMINSTATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_VMADMINSTATE:
                /* FIXME */
                //table_entry->old_vmAdminState = table_entry->vmAdminState;
                //table_entry->vmAdminState     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct vmTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_VMADMINSTATE:
                /* FIXME */
                //table_entry->vmAdminState     = table_entry->old_vmAdminState;
                //table_entry->old_vmAdminState = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
