/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef VMTABLE_H
#define VMTABLE_H

#include <net-snmp/agent/net-snmp-agent-includes.h>

/* function declarations */
void init_vmTable(void);
void initialize_table_vmTable(void);
Netsnmp_Node_Handler vmTable_handler;
Netsnmp_First_Data_Point  vmTable_get_first_data_point;
Netsnmp_Next_Data_Point   vmTable_get_next_data_point;

void vmTable_createEntryByIndex(long);
void vmTable_removeEntryByIndex(long);

/* column number definitions for table vmTable */
#define COLUMN_VMINDEX          1
#define COLUMN_VMNAME           2
#define COLUMN_VMUUID           3
#define COLUMN_VMOSTYPE         4
#define COLUMN_VMADMINSTATE     5
#define COLUMN_VMOPERSTATE      6
#define COLUMN_VMAUTOSTART      7
#define COLUMN_VMPERSISTENT     8
#define COLUMN_VMCURCPUNUMBER   9
#define COLUMN_VMMINCPUNUMBER   10
#define COLUMN_VMMAXCPUNUMBER   11
#define COLUMN_VMMEMUNIT        12
#define COLUMN_VMCURMEM         13
#define COLUMN_VMMINMEM         14
#define COLUMN_VMMAXMEM         15
#define COLUMN_VMUPTIME         16
#define COLUMN_VMCPUTIME        17

#endif /* VMTABLE_H */
